language: java

jdk:
  - oraclejdk8

os:
  - linux

before_install:
  - npm install -g elm
  - echo Installed elm `elm --version`
  - java -version

install:
  - ./gradlew assemble --no-daemon

script:
  - ./gradlew check --info --console=plain --max-workers=1 --no-daemon

deploy:
  - provider: script
    script: ORG_GRADLE_PROJECT_version=$TRAVIS_TAG ./gradlew publishPlugin
    on:
      tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

sudo: false

